line-length = 79

[lint]
select = [
  "E", # E: Style errors (PEP 8 formatting)
  "F", # F: Code errors (undefined variables, unused imports)
  "W", # W: Style warnings (trailing whitespace, missing newlines)
  "I", # I: Import sorting (isort rules)
]

fixable = ["ALL"]
